version: '3.3'

services:  
    python:
        build: .        
        container_name: app-python-flask        
        command: python app.py
        working_dir: /app
        volumes:
            - ./:/app     
        ports:
            - "5000:5000"   

